projects:
  VoiceBlast:
    schemaPath: src/graphql/schema.json
    includes:
      - src
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: mgn77rdrzfckhncoo7gfjfsonq
        maxDepth: 2
extensions:
  amplify:
    version: 3
